swagger: '2.0'
info:
  version: '0.1'
  title: Test
schemes: [ http ]
basePath: "/api"
paths:
  /biblio:
    get:
      x-mojo-to: "biblio#get"
      operationId: biblioGet
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: array
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/export:
    get:
      x-mojo-to: "biblio#check"
      operationId: biblioCheck
      consumes:
        - application/json
      parameters:
      - in: query
        name: marcxml
        type: string
        required: true
        description: Marcxml as string
      - in: query
        name: interface
        type: string
        description: Interface name
      responses:
        200:
          description: Ok status
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
    post:
      x-mojo-to: "biblio#export"
      operationId: biblioExport
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - localnumber
            - interface
            - marc
          properties:
            localnumber:
              type: integer
            marc:
              type: object
            interface:
              type: string
      responses:
        200:
          description: Ok status
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/config:
    get:
      x-mojo-to: "biblio#config"
      operationId: biblioConfig
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object