swagger: '2.0'
info:
  version: '0.1'
  title: Test
schemes: [ http ]
basePath: "/api"
paths:
  /biblio:
    get:
      x-mojo-to: "biblio#get"
      operationId: biblioGet
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/{biblionumber}:
    post:
      x-mojo-to: "biblio#add"
      operationId: biblioAdd
      consumes:
        - application/json
      parameters:
        - in: path
          name: biblionumber
          type: integer
          required: true
        - in: query
          name: userid
          type: string
        - in: query
          name: password
          type: string
      responses:
        200:
          description: Ok status
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
    put:
      x-mojo-to: "biblio#update"
      operationId: biblioUpdate
      consumes:
        - application/json
      parameters:
        - in: path
          name: biblionumber
          type: integer
          required: true
        - in: query
          name: userid
          type: string
        - in: query
          name: password
          type: string
      responses:
        200:
          description: Ok status
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/config:
    get:
      x-mojo-to: "biblio#config"
      operationId: biblioConfig
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object