swagger: '2.0'
info:
  version: '0.1'
  title: Test
schemes: [ http ]
basePath: "/api"
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: Authorization
security:
  - APIKey: []
paths:
  /biblio:
    get:
      x-mojo-to: "biblio#get"
      operationId: biblioGet
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: array
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/export:
    post:
      x-mojo-to: "biblio#export"
      operationId: biblioExport
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - target_id
            - interface
            - marc
          properties:
            targetid:
              type: integer
            marc:
              type: [object, string]
            interface:
              type: string
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/search:
    get:
      x-mojo-to: "biblio#check"
      operationId: biblioExportCheck
      consumes:
        - application/json
      parameters:
      - in: query
        name: marcxml
        type: string
        required: true
        description: Marcxml as string
      - in: query
        name: interface
        required: true
        type: string
        description: Interface name
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/active:
    post:
      x-mojo-to: "biblio#activate"
      operationId: biblioSetActive
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - interface_name
            - target_id
            - marcxml
          properties:
            interface:
              type: string
              description: Name of the interface
            target_id:
              type: integer
              description: Records id on local environment
            marcxml:
              type: string
              description: Marcxml
            updated:
              type: string
              description: Datetime of record's update
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      Authorization:
        type: string