swagger: '2.0'
info:
  version: '0.1'
  title: Test
schemes: [ http ]
basePath: "/api"
paths:
  /biblio:
    get:
      x-mojo-to: "biblio#get"
      operationId: biblioGet
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: array
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/export:
    post:
      x-mojo-to: "biblio#export"
      operationId: biblioExport
      consumes:
        - application/json
      parameters:
      - in: query
        name: interface_id
        type: integer
        required: true
        description: Interface id
      - in: query
        name: localnumber
        type: integer
        required: true
        description: Local biblionumber
      - in: query
        name: remotenumber
        type: integer
        description: Remote biblionumber
      responses:
        200:
          description: Ok status
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/config:
    get:
      x-mojo-to: "biblio#config"
      operationId: biblioConfig
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object