swagger: '2.0'
info:
  version: '0.1'
  title: Biblio exporter
schemes: [ http ]
basePath: "/api"
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: Authorization
security:
  - APIKey: []
paths:
  /biblio:
    get:
      x-mojo-to: "biblio#list"
      operationId: biblioList
      consumes:
        - application/json
      parameters:
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/{id}:
    get:
      x-mojo-to: "biblio#get"
      operationId: biblioGet
      consumes:
        - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        description: Get export report from biblio
      responses:
        200:
          description: Ok status
          schema:
            type: array
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/record/{id}:
    get:
      x-mojo-to: "biblio#record"
      operationId: biblioRecord
      consumes:
        - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        description: Get record
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/report/{interface_name}:
    get:
      x-mojo-to: "biblio#report"
      operationId: biblioInterface
      consumes:
        - application/json
      parameters:
      - in: path
        name: interface_name
        required: true
        type: string
        description: Get export report from interface
      - in: body
        name: body
        schema:
          type: object
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/{id}/force:
    put:
      x-mojo-to: "biblio#force"
      operationId: biblioForceExport
      consumes:
        - application/json
      parameters:
      - in: path
        name: id
        required: true
        type: integer
        description: Force export biblio
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/export:
    post:
      x-mojo-to: "biblio#export"
      operationId: biblioExport
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - source_id
            - interface
            - marc
          properties:
            target_id:
              type: [integer, string, "null"]
            source_id:
              type: [integer, string]
            marc:
              type: [object, string]
            interface:
              type: string
            username:
              type: string
            parent_id:
              type: [integer, string, "null"]
            force: 
              type: [integer, "null"]
            componentparts:
              type: [integer, "null"]
            fetch_interface:
              type: [string, "null"]
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/search:
    post:
      x-mojo-to: "biblio#check"
      operationId: biblioExportCheck
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - marcxml
            - interface
          properties:
            marcxml:
              type: string
            interface:
              type: string
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/active:
    post:
      x-mojo-to: "biblio#activate"
      operationId: biblioSetActive
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - interface_name
            - target_id
            - marcxml
          properties:
            interface:
              type: string
              description: Name of the interface
            target_id:
              type: integer
              description: Records id on local environment
            marcxml:
              type: string
              description: Marcxml
            updated:
              type: string
              description: Datetime of record's update
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
  /biblio/broadcast:
    post:
      x-mojo-to: "biblio#broadcast"
      operationId: biblioBroadCast
      consumes:
        - application/x-www-form-urlencoded
      parameters:
      - in: body
        name: body
        schema:
          type: object
          required:
            - source_id
            - marcxml
            - updated
          properties:
            source_id:
              type: integer
              description: Records id on local environment
            marcxml:
              type: string
              description: Marcxml
            updated:
              type: string
              description: Datetime of record's update
      responses:
        200:
          description: Ok status
          schema:
            type: object
        401:
          $ref: "#/responses/UnauthorizedError"
        404:
          description: Not found
          schema:
            type: object
        500:
          description: Internal server error
          schema:
            type: object
responses:
  UnauthorizedError:
    description: API key is missing or invalid
    headers:
      Authorization:
        type: string